### ISSUE TITLE
Pickle load error on Python 3.10.12

### ISSUE THREAD

**Issue by classAndrew** [yuzhenmao/ScRAT#1]
Hi, I downloaded patient_id.pkl from [here](https://figshare.com/articles/dataset/SC4/21397257) but I get this error when running `bash run.sh`:

```py
Namespace(seed=100, batch_size=256, learning_rate=0.01, weight_decay=0.0001, epochs=100, task='stage', emb_dim=128, h_dim=128, dropout=0.3, layers=1, heads=8, train_sample_cells=500, test_sample_cells=500, train_num_sample=20, test_num_sample=50, model='Transformer', dataset=None, inter_only=True, same_pheno=-1, augment_num=300, alpha=0.5, repeat=1, all=0, min_size=10000, n_splits=2, pca=True, mix_type=1, norm_first=False, warmup=False, top_k=1)
Traceback (most recent call last):
  File "/Users/andrew/ScRAT/main.py", line 281, in <module>
    p_idx, labels_, cell_type, patient_id, data, cell_type_large = Covid_data(args)
  File "/Users/andrew/ScRAT/dataloader.py", line 74, in Covid_data
    patient_id = pickle.load(a_file)
_pickle.UnpicklingError: invalid load key, '*'.
```

Is the file corrupted? The rest are loaded normally.

**Comment by yuzhenmao** [comment]
Hi! Thank you for pointing this out. Yes, it is corrupted for some reason. Please try this one instead: https://drive.google.com/file/d/1mBOnfxLuFJWLjgKO6AsA2pcE0LMCEF7P/view?usp=sharing. We will also update the file on the original website ASAP.

**Comment by yenyilin** [comment]
@classAndrew Please give it a try using the updated file.

**Comment by classAndrew** [comment]
Thank you! It works now.
